"""
The local voice engine: microphone → speech recognition → any LLM with tools →
speech → speakers. Used for every brain except Gemini Live.

HOW IT FITS INTO THE EXISTING APP
    main.py's JarvisLive is built around one object, `self.session`, the Gemini
    Live connection. Everything else — the tool dispatcher, memory, undo,
    vision capture, the wake word, push-to-talk, the phone dashboard, the
    morning briefing, proactive check-ins, hardware alerts, the avatar's
    lip-sync and the echo guard — talks to that object or to two queues.

    So this engine does not rebuild any of that. It is a mixin that replaces
    exactly the parts that belonged to Gemini:

      * `self.session` becomes LocalSession, which accepts the same calls
        (send_client_content, send_realtime_input) and turns them into requests
        for the local brain;
      * the microphone feeds a voice-activity detector and speech recognition
        instead of a websocket;
      * the reply is generated by core.llm with the SAME tool declarations and
        run through the SAME `_execute_tool`, and spoken by core.tts_engine into
        the SAME `audio_in_queue` that `_play_audio` already drains — so the
        avatar's mouth, the waveform and the echo guard work unchanged.

HUMAN-LIKE CONVERSATION
    * Barge-in: speak while it is talking and it stops and listens. What the
      microphone hears during a reply is transcribed and compared with what the
      assistant just said; its own echo is ignored, a new voice interrupts.
    * Ambient mode: it listens to the whole room, keeps a local transcript, and
      answers only when called by name — or for a while after it last spoke, the
      way a person stays in a conversation they have joined.
    * It speaks the first sentence while the rest is still being written.
    * Voice confirmation: "confirm" / "cancel" answer the on-screen gate for
      shutdown, restart and dangerous commands, decided by the words heard, not
      by the model.
"""
from __future__ import annotations

import asyncio
import collections
import json
import platform
import queue
import random
import threading
import time
import traceback
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from types import SimpleNamespace

import numpy as np

from core import attention, brain_config, journal, llm, runtime
from core import confirm as confirm_gate
from core.speech_text import SpeechStream, visible_text
from core.stt_engine import create_stt, is_hallucination, normalize_lang
from core.tts_engine import create_tts

SEND_SR = 16000
PLAY_SR = 24000
_SLICE = 2400                   # bytes per queued audio slice (50 ms at 24 kHz)

# Tools that finish instantly and have no outside effect: no spoken
# acknowledgement is needed before them.
_INSTANT_TOOLS = {"save_memory", "recall_memory", "undo", "close_camera", "system_status",
                  "computer_settings", "conversation_log", "open_app", "screen_process",
                  "manage_monitor", "face_id", "weather_report"}

_ACKS = {
    "en": ["On it.", "Right away.", "One moment.", "Working on it.", "Give me a second."],
    "hi": ["ठीक है, एक पल।", "अभी करता हूँ।", "एक सेकंड।"],
    "es": ["Un momento.", "Enseguida."], "fr": ["Un instant.", "Tout de suite."],
    "de": ["Einen Moment.", "Sofort."], "tr": ["Bir saniye.", "Hemen."],
    "pt": ["Um momento.", "Já vou."], "it": ["Un attimo.", "Subito."],
    "ru": ["Секунду.", "Сейчас."], "ar": ["لحظة من فضلك."], "ja": ["少々お待ちください。"],
}


def _level(samples) -> float:
    try:
        x = np.asarray(samples, dtype=np.float32)
        if x.size == 0:
            return 0.0
        rms = float(np.sqrt(np.mean(x * x)))
    except Exception:
        return 0.0
    if rms <= 60.0:
        return 0.0
    return min(1.0, (rms - 60.0) / 2540.0)


@dataclass
class Request:
    text: str
    source: str = "voice"            # voice | typed | system | remote
    images: list = field(default_factory=list)
    lang: str = ""


class LocalSession:
    """Accepts the calls main.py makes on a Gemini Live session."""

    def __init__(self, eng: "LocalEngineMixin"):
        self._eng = eng

    async def send_client_content(self, turns=None, turn_complete=True, **_kw):
        texts, images = [], []
        items = turns if isinstance(turns, (list, tuple)) else [turns]
        for t in items:
            if not isinstance(t, dict):
                continue
            for p in t.get("parts") or []:
                if not isinstance(p, dict):
                    continue
                if p.get("text"):
                    texts.append(str(p["text"]))
                elif isinstance(p.get("inline_data"), dict):
                    d = p["inline_data"]
                    images.append({"mime": d.get("mime_type", "image/jpeg"), "data": d.get("data", "")})
        if texts or images:
            self._eng._submit("\n".join(texts), images=images, source="system")

    async def send_realtime_input(self, audio=None, **_kw):
        data = getattr(audio, "data", None)
        if data is None and isinstance(audio, dict):
            data = audio.get("data")
        if data:
            self._eng._feed_remote_audio(data)

    async def send_tool_response(self, **_kw):
        return None

    async def receive(self):          # never used by the local engine
        if False:
            yield None


class LocalEngineMixin:
    """Mixed in before JarvisLive: `class LocalJarvis(LocalEngineMixin, JarvisLive)`."""

    INLINE_TOOLS: list = []

    # ── construction ─────────────────────────────────────────────────────────
    def __init__(self, ui):
        super().__init__(ui)
        self.engine_kind = "local"
        self._history: list[dict] = []
        self._earlier = ""                 # digest of history that no longer fits
        self._hist_lock = threading.RLock()
        self._req_q: asyncio.Queue | None = None
        self._mic_q: queue.Queue = queue.Queue(maxsize=600)
        self._utt_q: queue.Queue = queue.Queue(maxsize=12)
        self._tts_q: queue.Queue = queue.Queue()
        self._tts_pending = 0
        self._tts_cond = threading.Condition()
        self._cancel = threading.Event()
        self._turn_id = 0
        self._busy = False
        self._stt = None
        self._stt_cfg = None
        self._stt_ready = threading.Event()
        self._tts = None
        self._segmenter = None
        self._seg_during = False
        self._spoken: collections.deque = collections.deque(maxlen=40)
        self._last_reply_end = 0.0
        self._last_lang = ""
        self._workers = False
        self._brain_ok = False
        self._pull_started: set[str] = set()
        self._stt_wait_note = 0.0
        self._asst_name = brain_config.assistant_name()
        runtime.set_engine(self)

    # ── what the rest of the app calls ───────────────────────────────────────
    def _all_tool_decls(self) -> list:
        decls = list(self.INLINE_TOOLS) + self._action_registry.get_tool_declarations() \
            + self._plugin_registry.get_tool_declarations()
        try:
            from core import mcp_client
            decls += mcp_client.manager().gemini_declarations()
        except Exception:
            pass
        b = brain_config.get_brain()
        disabled = set(b.get("disabled_tools") or [])
        profile = str(b.get("tool_profile") or "auto").lower()
        if profile == "auto" and b.get("provider") in ("ollama", "lmstudio"):
            size = llm.model_size_b(llm.settings_for("chat"))
            profile = "lean" if (size is not None and size < 6.5) else "full"
        if profile == "lean":
            disabled |= set(brain_config.LEAN_HIDDEN)
        return [d for d in decls if d.get("name") not in disabled]

    def _submit(self, text: str, images=None, source: str = "system", lang: str = "") -> None:
        req = Request(text=text or "", source=source, images=list(images or []), lang=lang)
        loop = self._loop
        if loop is None or self._req_q is None:
            return
        try:
            loop.call_soon_threadsafe(self._req_q.put_nowait, req)
        except RuntimeError:
            pass

    def _on_text_command(self, text: str):
        if not self._loop or not self.session:
            return
        if self._wake_enabled and not self._awake:
            self.ui.write_log("SYS: I'm asleep — say 'Hey Jarvis' or tap WAKE NOW first.")
            return
        if self._is_speaking or self._busy:
            self.interrupt()
        self._last_user_speech = time.monotonic()
        self._session_log.append(f"User: {text}")
        journal.append("user", text, True, via="typed")
        self._submit(text, source="typed")

    def speak_error(self, tool_name: str, error: str):
        # The error already goes back to the model as the tool result, inside
        # the same turn; a second, separate "tell the user" turn is noise here.
        self.ui.write_log(f"ERR: {tool_name} — {str(error)[:120]}")

    def plugin_say(self, instruction: str) -> None:
        """A plugin wants something said while its tool is still running."""
        if not self._busy:
            self._submit(instruction, source="system")
            return

        def work():
            try:
                line = llm.complete(
                    f"Turn this instruction into ONE short sentence to say to the user, "
                    f"in {self._lang_name()}. Output only the sentence.\n\n{instruction}",
                    role="fast", max_tokens=80, timeout=20)
            except Exception:
                line = ""
            if line:
                self._speak(line.strip().strip('"'), self._turn_id)
        threading.Thread(target=work, daemon=True).start()

    def interrupt(self) -> None:
        self._cancel.set()
        self._turn_id += 1
        try:
            while True:
                self._tts_q.get_nowait()
                with self._tts_cond:
                    self._tts_pending = max(0, self._tts_pending - 1)
                    self._tts_cond.notify_all()
        except queue.Empty:
            pass
        super().interrupt()

    def set_speaking(self, value: bool):
        was = self._is_speaking
        super().set_speaking(value)
        if was and not value:
            self._last_reply_end = time.monotonic()

    def reload_plugins(self) -> str:
        from core.plugin_loader import discover_plugins
        base = Path(__file__).resolve().parent.parent
        core_names = {t["name"] for t in self.INLINE_TOOLS} | self._action_registry.names()
        self._plugin_registry = discover_plugins(
            plugins_dir=base / "plugins", core_tool_names=core_names,
            logger=lambda m: print(f"[Plugins] {m}"),
            notify=lambda m: self.ui.write_log(f"SYS: {m}"))
        self.ui.get_plugins = self._plugin_registry.list_for_ui
        self.ui.get_plugin_settings = self._plugin_registry.settings_schemas
        n = len(self._plugin_registry.get_tool_declarations())
        return f"Reloaded plugins: {n} active."

    # ── helpers ──────────────────────────────────────────────────────────────
    def _lang_name(self) -> str:
        names = {"en": "English", "hi": "Hindi", "es": "Spanish", "fr": "French", "de": "German",
                 "tr": "Turkish", "pt": "Portuguese", "it": "Italian", "ru": "Russian",
                 "ar": "Arabic", "ja": "Japanese", "zh": "Chinese", "bn": "Bengali", "ur": "Urdu",
                 "ta": "Tamil", "te": "Telugu", "mr": "Marathi"}
        return names.get(self._last_lang, "the user's language")

    def _log_async(self, text: str) -> None:
        try:
            self.ui.write_log(text)
        except Exception:
            print(text)

    def _call_in_loop(self, fn, *args) -> None:
        loop = self._loop
        if loop is not None:
            try:
                loop.call_soon_threadsafe(fn, *args)
            except RuntimeError:
                pass

    # ── startup ──────────────────────────────────────────────────────────────
    def _start_workers(self) -> None:
        if self._workers:
            return
        self._workers = True
        for target, name in ((self._vad_worker, "local-vad"), (self._stt_worker, "local-stt"),
                             (self._tts_worker, "local-tts")):
            threading.Thread(target=target, daemon=True, name=name).start()

    def _setup_voice(self) -> None:
        """(Re)create speech recognition and voice from the current settings."""
        from core.vad import Segmenter
        v = brain_config.get_voice_cfg()
        self._segmenter = Segmenter(self._on_utterance, on_start=self._on_speech_start,
                                    threshold=v["vad_threshold"], end_silence_ms=v["end_silence_ms"])
        stt_cfg = (v.get("stt_engine"), v.get("stt_model"), v.get("stt_device"),
                   v.get("stt_language"), v.get("stt_api_model"), v.get("stt_api_key"),
                   v.get("stt_base_url"), brain_config.assistant_name())
        if self._stt is None or stt_cfg != self._stt_cfg:
            self._stt_ready.clear()
            self._stt = create_stt(log=self._log_async)
            self._stt_cfg = stt_cfg

            def load_stt():
                try:
                    self._stt.load()
                    self._stt_ready.set()
                except Exception as e:
                    self._log_async(f"ERR: Speech recognition failed to load — {str(e)[:200]}")
                    self._log_async("SYS: You can still type commands. Check ⚙ → AI BRAIN → Speech.")
            threading.Thread(target=load_stt, daemon=True, name="stt-load").start()
        self._tts = create_tts(log=self._log_async)
        threading.Thread(target=self._tts.load, daemon=True, name="tts-load").start()

    def _check_brain(self) -> None:
        """Runs off-thread at every (re)connect: is the brain reachable, is the
        model there, and is it warm? Problems are explained in the log."""
        b = brain_config.get_brain()
        s = llm.settings_for("chat")
        label = brain_config.PROVIDER_LABELS.get(b["provider"], b["provider"])
        if s.provider == "ollama":
            if not llm.ensure_ollama_running(s):
                self._brain_ok = False
                self._log_async("ERR: Ollama is not running. Install it from https://ollama.com/download "
                                "and start it — I will keep trying.")
                return
        ok, msg = llm.ping(s)
        if not ok and s.provider == "ollama" and "not downloaded" in msg and s.model not in self._pull_started:
            self._pull_started.add(s.model)
            self._log_async(f"SYS: Downloading the brain model '{s.model}' — this happens once.")
            last = [-1]

            def prog(status, frac):
                pct = int(frac * 100)
                if pct >= last[0] + 10 or status == "success":
                    last[0] = pct
                    self._log_async(f"SYS: Model download {status} {pct}%")
            ok, msg = llm.ollama_pull(s.model, progress=prog, s=s)
            if ok:
                self._log_async(f"SYS: '{s.model}' downloaded.")
                ok, msg = llm.ping(s)
        if not ok:
            self._brain_ok = False
            self._log_async(f"ERR: Brain unavailable — {msg}")
            return
        self._brain_ok = True
        model = s.model or "(loaded model)"
        if s.provider not in ("ollama", "lmstudio"):
            self._log_async(f"SYS: Brain: {label} — {model}. Ready.")
            return
        self._log_async(f"SYS: Brain: {label} — {model}. Warming up…")
        t0 = time.monotonic()
        try:
            msgs = [{"role": "system", "content": self._system_prompt()},
                    {"role": "user", "content": "Reply with the single word: ready"}]
            llm.chat(msgs, self._all_tool_decls(), s=s, max_tokens=4)
            self._log_async(f"SYS: Brain ready ({time.monotonic() - t0:.1f}s).")
        except Exception as e:
            self._log_async(f"ERR: Brain warm-up failed — {str(e)[:200]}")

    # ── main loop ────────────────────────────────────────────────────────────
    async def run(self):
        self._loop = asyncio.get_event_loop()
        self._reconnect_event = asyncio.Event()
        self._req_q = asyncio.Queue()
        await self._start_services()
        self._start_workers()
        journal.prune()

        while True:
            try:
                self.ui.set_state("THINKING")
                self._setup_voice()
                threading.Thread(target=self._check_brain, daemon=True, name="brain-check").start()

                async with asyncio.TaskGroup() as tg:
                    self.session = LocalSession(self)
                    self.audio_in_queue = asyncio.Queue()
                    self.out_queue = asyncio.Queue(maxsize=200)
                    self._turn_done_event = asyncio.Event()
                    self._pending_vision = None
                    self._vision_busy = False
                    self._interrupted = False

                    if self._wake_enabled:
                        self._ensure_wake_detector()
                        self._awake = False
                        self.ui.set_state("SLEEPING")
                        self.ui.write_log("SYS: Online — sleeping. Say 'Hey Jarvis' to wake me.")
                    else:
                        self._awake = True
                        self.ui.set_state("LISTENING")
                        mode = brain_config.get_senses()["listen_mode"]
                        self.ui.write_log("SYS: Online — " + (
                            "ambient listening: I answer when you say my name."
                            if mode == "ambient" else "listening."))
                    if self._dashboard:
                        await self._dashboard.broadcast({"type": "status", "state": "active"})

                    self._reconnect_event.clear()
                    tg.create_task(self._watch_reconnect())
                    tg.create_task(self._send_realtime())
                    tg.create_task(self._listen_audio())
                    tg.create_task(self._brain_loop())
                    tg.create_task(self._play_audio())
                    tg.create_task(self._run_system_monitor())
                    tg.create_task(self._run_background_monitor())
                    tg.create_task(self._run_proactive_mode())
                    tg.create_task(self._run_sleep_watch())
                    tg.create_task(self._run_scheduler())
                    if self._dashboard:
                        tg.create_task(self._relay_phone_audio())
                    from memory.config_manager import get_brief_enabled
                    if not self._briefing_sent and get_brief_enabled() and self._awake:
                        self._briefing_sent = True
                        tg.create_task(self._send_startup_briefing())
            except (KeyboardInterrupt, SystemExit):
                raise
            except BaseException as e:
                from main import _is_reconnect_signal, _keep_context_of   # noqa: PLC0415
                if _is_reconnect_signal(e):
                    if not _keep_context_of(e):
                        with self._hist_lock:
                            self._history.clear()
                            self._earlier = ""
                    self.interrupt()
                    continue
                print(f"[Local] session error: {type(e).__name__}: {e}")
                traceback.print_exc()
                self.ui.write_log(f"ERR: Voice engine restarted after an error — {str(e)[:120]}")
                await asyncio.sleep(3)
            finally:
                self.session = None
                if len(self._session_log) >= 3:
                    asyncio.create_task(self._save_session_summary())
            self.set_speaking(False)

    # ── microphone ───────────────────────────────────────────────────────────
    async def _listen_audio(self):
        import sounddevice as sd
        from core import audio_devices
        from memory.config_manager import get_input_device

        def callback(indata, frames, time_info, status):
            if self._wake_enabled and not self._awake:
                det = self._wake_detector
                if det is not None:
                    det.feed(indata)
                return
            if self._ptt_enabled and not self._ptt_held:
                return
            if self.ui.muted or self._phone_active:
                return
            block = indata[:, 0].copy() if indata.ndim > 1 else indata.copy()
            speaking = self._is_speaking or self._tail_active()
            try:
                self._mic_q.put_nowait((block, speaking))
            except queue.Full:
                pass
            if not speaking:
                try:
                    self.ui.set_audio_level(_level(block))
                except Exception:
                    pass

        def open_mic(dev):
            return sd.InputStream(samplerate=SEND_SR, channels=1, dtype="int16",
                                  blocksize=1024, device=dev, callback=callback)

        name = get_input_device()
        dev = audio_devices.resolve(name, "input")
        try:
            stream = open_mic(dev)
        except Exception as e:
            if dev is None:
                self.ui.write_log(f"ERR: No usable microphone — {e}. You can still type.")
                while True:
                    await asyncio.sleep(3600)
            self.ui.write_log(f"SYS: Microphone '{name}' unavailable — using system default.")
            stream = open_mic(None)
        with stream:
            print("[Local] 🎤 Mic stream open")
            while True:
                await asyncio.sleep(0.1)

    def _feed_remote_audio(self, data: bytes) -> None:
        """Phone microphone audio from the dashboard (16 kHz int16)."""
        try:
            block = np.frombuffer(data, dtype=np.int16).copy()
            self._mic_q.put_nowait((block, self._is_speaking))
        except Exception:
            pass

    def _vad_worker(self) -> None:
        while True:
            try:
                block, speaking = self._mic_q.get()
                seg = self._segmenter
                if seg is None:
                    continue
                # While we talk, cut what the mic hears into short pieces so an
                # interruption is noticed within seconds, not after the reply.
                seg._max_frames = 125 if speaking else 940
                if speaking:
                    self._seg_during = True
                seg.feed(block)
            except Exception as e:
                print(f"[Local] VAD error: {e}")
                time.sleep(0.05)

    def _on_speech_start(self) -> None:
        self._seg_during = self._is_speaking or self._tail_active()
        if not self._is_speaking and not self._busy:
            try:
                self.ui.set_state("LISTENING")
            except Exception:
                pass

    def _on_utterance(self, samples: np.ndarray) -> None:
        during = self._seg_during or self._is_speaking
        self._seg_during = False
        try:
            self._utt_q.put_nowait((samples, during))
        except queue.Full:
            pass

    def _stt_worker(self) -> None:
        while True:
            samples, during = self._utt_q.get()
            if during and not brain_config.get_senses().get("barge_in", True):
                continue      # our own voice, most likely — not worth the CPU
            try:
                if not self._stt_ready.wait(timeout=0.5):
                    now = time.monotonic()
                    if now - self._stt_wait_note > 20:
                        self._stt_wait_note = now
                        self._log_async("SYS: Speech recognition is still loading — "
                                        "type your command meanwhile.")
                    continue
                text, lang = self._stt.transcribe(samples)
            except Exception as e:
                print(f"[Local] STT error: {e}")
                self._log_async(f"ERR: Speech recognition — {str(e)[:120]}")
                continue
            if text and not is_hallucination(text):
                loop = self._loop
                if loop is not None:
                    asyncio.run_coroutine_threadsafe(self._on_heard(text, lang, during), loop)

    # ── deciding what to do with what was heard ──────────────────────────────
    def _recent_spoken(self, seconds: float = 20.0) -> list[str]:
        now = time.monotonic()
        return [t for (ts, t) in list(self._spoken) if now - ts <= seconds]

    async def _on_heard(self, text: str, lang: str, during: bool) -> None:
        text = " ".join(text.split())
        senses = brain_config.get_senses()
        name = (self._asst_name or "JARVIS").strip()
        ws = attention.words(text)

        # 1. A spoken answer to a pending confirmation.
        if senses.get("voice_confirm", True) and confirm_gate.pending_title():
            ans = attention.confirm_answer(text)
            if ans is not None:
                self.ui.write_log(f"You: {text}")
                confirm_gate.resolve(ans)
                self._speak("Confirmed." if ans else "Cancelled.", self._turn_id)
                return

        # 2. Heard while we were talking: our own echo, or the user cutting in.
        named = attention.addressed_by_name(text, name, senses.get("name_aliases") or [])
        if during or self._is_speaking:
            recent = self._recent_spoken()
            frac = attention.echo_fraction(text, recent)
            named_new = named and not any(attention.addressed_by_name(r, name) for r in recent)
            stop = attention.is_stop_command(text) and frac < 0.9
            if stop or named_new or (frac < 0.5 and len(ws) >= 2):
                if senses.get("barge_in", True) or stop:
                    self.interrupt()
                    if stop and len(ws) <= 3:
                        self.ui.write_log(f"You: {text}")
                        return
                else:
                    return
            else:
                return      # our own voice coming back

        if lang:
            self._last_lang = normalize_lang(lang)

        # 3. Is it for us?
        mode = senses.get("listen_mode", "active")
        follow = float(senses.get("follow_up_seconds", 20) or 0)
        in_conversation = (time.monotonic() - self._last_reply_end) < follow or self._busy
        addressed = True
        if mode == "ambient":
            addressed = named or in_conversation
            if not addressed and senses.get("smart_interject") and len(ws) >= 4:
                addressed = await asyncio.to_thread(self._should_interject, text)

        # 4. Owner-only: obey only while the owner's face is in view.
        if addressed and senses.get("owner_only") and senses.get("face_presence"):
            if runtime.get_state("owner_present") is False:
                journal.append("room", text, False)
                self.ui.write_log(f"SYS: (ignored — owner not in view) {text}")
                return

        journal.append("user" if addressed else "room", text, addressed)
        if not addressed:
            self.ui.write_log(f"Heard: {text}")
            return

        if self._wake_enabled and not self._awake:
            return
        self._last_user_speech = time.monotonic()
        clean = attention.strip_name(text, name) if (mode == "ambient" and named) else text
        self.ui.write_log(f"You: {text}")
        self._session_log.append(f"User: {text}")
        if self._dashboard:
            asyncio.create_task(self._dashboard.broadcast({
                "type": "log", "speaker": "user", "text": text, "ts": datetime.now().isoformat()}))
        self._submit(clean, source="voice", lang=self._last_lang)

    def _should_interject(self, text: str) -> bool:
        try:
            ctx = journal.search("", "last_10_minutes", limit=12)
            ans = llm.complete(
                f"You are {self._asst_name}, an assistant quietly listening in a room. Recent talk:\n"
                f"{ctx}\n\nLatest line: \"{text}\"\n"
                "Would a thoughtful assistant speak up now — a direct question to the room it "
                "can answer, a factual mistake worth correcting, or a request for help? "
                "Answer only YES or NO.", role="fast", max_tokens=3, timeout=15)
            return ans.strip().upper().startswith("Y")
        except Exception:
            return False

    # ── the brain ────────────────────────────────────────────────────────────
    def _system_prompt(self) -> str:
        from main import _describe_limits, _render_prompt   # noqa: PLC0415
        from memory.memory_manager import format_memory_for_prompt, load_memory
        base = Path(__file__).resolve().parent
        try:
            tmpl = (base / "prompt_local.txt").read_text(encoding="utf-8")
        except Exception:
            tmpl = "You are {assistant_name}, a helpful voice assistant on {platform}. Today is {date}."
        cfg = {}
        try:
            cfg = json.loads(brain_config.CONFIG_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
        self._asst_name = (cfg.get("assistant_name") or "JARVIS").strip()
        user = (cfg.get("user_name") or "").strip()
        body = _render_prompt(tmpl, {
            "assistant_name": self._asst_name,
            "platform": f"{platform.system()} {platform.release()}",
            "date": datetime.now().strftime("%A, %d %B %Y"),
            "limits": _describe_limits(has_vision=True, has_mic=True),
        })
        addr = (f"Call the user '{user}'." if user else
                "Address the user respectfully (\"sir\" in English, the natural equivalent in other languages).")
        parts = [f"[IDENTITY]\nYour name is {self._asst_name}. {addr}"]
        try:
            mem = format_memory_for_prompt(load_memory())
            if mem:
                parts.append(mem)
        except Exception:
            pass
        parts.append(body)
        if self._earlier:
            parts.append("[EARLIER IN THIS CONVERSATION]\n" + self._earlier)
        return "\n\n".join(parts)

    def _trim_history(self, num_ctx: int) -> None:
        budget = int(num_ctx * 1.3)
        with self._hist_lock:
            h = self._history
            # Images are expensive: keep them only in the latest exchange.
            last_user = max((i for i, m in enumerate(h) if m.get("role") == "user"), default=-1)
            for i, m in enumerate(h):
                if i < last_user and m.get("images"):
                    m.pop("images", None)
                    m["content"] = str(m.get("content", "")) + " [image no longer attached]"

            def size() -> int:
                return sum(len(str(m.get("content") or "")) + 80 * len(m.get("tool_calls") or [])
                           for m in h)
            dropped = []
            while size() > budget:
                starts = [i for i, m in enumerate(h) if m.get("role") == "user"]
                if len(starts) < 2:
                    break
                cut = starts[1]
                dropped.extend(h[:cut])
                del h[:cut]
            if dropped:
                notes = []
                for m in dropped:
                    c = visible_text(str(m.get("content") or ""))
                    if m.get("role") == "user" and c:
                        notes.append("User: " + c[:160])
                    elif m.get("role") == "assistant" and c:
                        notes.append("You: " + c[:160])
                self._earlier = ("\n".join(([self._earlier] if self._earlier else []) + notes))[-1500:]

    def _speak(self, sentence: str, turn_id: int) -> None:
        sentence = (sentence or "").strip()
        if not sentence:
            return
        self._spoken.append((time.monotonic(), sentence))
        with self._tts_cond:
            self._tts_pending += 1
        self._tts_q.put((turn_id, sentence, self._last_lang))

    def _wait_tts(self, turn_id: int, timeout: float = 180.0) -> None:
        deadline = time.monotonic() + timeout
        with self._tts_cond:
            while self._tts_pending > 0 and time.monotonic() < deadline:
                if turn_id != self._turn_id:
                    return
                self._tts_cond.wait(timeout=0.25)

    def _tts_worker(self) -> None:
        while True:
            tid, text, lang = self._tts_q.get()
            try:
                if tid != self._turn_id or self._tts is None:
                    continue
                first = True
                for chunk in self._tts.synth(text, lang):
                    if tid != self._turn_id:
                        break
                    self._call_in_loop(self._enqueue_audio, tid, chunk, text if first else "")
                    first = False
            except Exception as e:
                print(f"[Local] TTS error: {e}")
                self._log_async(f"ERR: Voice output — {str(e)[:120]}")
            finally:
                with self._tts_cond:
                    self._tts_pending = max(0, self._tts_pending - 1)
                    self._tts_cond.notify_all()

    def _enqueue_audio(self, tid: int, pcm: np.ndarray, text: str) -> None:
        if tid != self._turn_id or self.audio_in_queue is None:
            return
        if self._turn_done_event is not None and self._turn_done_event.is_set():
            self._turn_done_event.clear()
        if text:
            self._visemes.feed_text(text)
        data = np.asarray(pcm, dtype=np.int16).tobytes()
        for i in range(0, len(data), _SLICE):
            self.audio_in_queue.put_nowait(data[i:i + _SLICE])

    def _finish_turn_audio(self) -> None:
        if self._turn_done_event is not None:
            self._turn_done_event.set()

    async def _brain_loop(self):
        while True:
            req = await self._req_q.get()
            # Several things said in a row while we were busy become one request.
            while not self._req_q.empty():
                nxt = self._req_q.get_nowait()
                if nxt.source in ("voice", "typed") and req.source in ("voice", "typed") and not nxt.images:
                    req.text = f"{req.text} {nxt.text}".strip()
                else:
                    await self._run_turn(req)
                    req = nxt
            await self._run_turn(req)

    async def _run_turn(self, req: Request) -> None:
        if not req.text and not req.images:
            return
        self._busy = True
        self._cancel.clear()
        self._turn_id += 1
        tid = self._turn_id
        self._visemes.reset()
        if self._turn_done_event is not None:
            self._turn_done_event.clear()
        self.ui.set_state("THINKING")
        try:
            final = await asyncio.to_thread(self._agent_turn, req, tid)
        except Exception as e:
            traceback.print_exc()
            final = ""
            self.ui.write_log(f"ERR: {str(e)[:200]}")
        finally:
            self._busy = False
        # Let the voice finish before the turn is marked done.
        await asyncio.to_thread(self._wait_tts, tid)
        if tid == self._turn_id:
            self._finish_turn_audio()
            if not self._is_speaking and self.audio_in_queue is not None and self.audio_in_queue.empty():
                if not self.ui.muted:
                    self.ui.set_state("LISTENING")
                self._last_reply_end = time.monotonic()
        shown = "\n".join(getattr(self, "_turn_shown", []) or []).strip()
        if shown and "```" in shown:
            try:
                self.ui.show_content("REPLY", shown)
            except Exception:
                pass
        if final:
            self.ui.write_log(f"{self._asst_name}: {final}")
            self._session_log.append(f"{self._asst_name}: {final}")
            journal.append(self._asst_name, final, None)
            runtime.emit_assistant_text(final)
            if self._dashboard:
                asyncio.create_task(self._dashboard.broadcast({
                    "type": "log", "speaker": "jarvis", "text": final,
                    "ts": datetime.now().isoformat()}))
        if self._vision_close_pending:
            self._vision_close_pending = False

            async def _close():
                await asyncio.sleep(2.0)
                self.ui.stop_camera_stream()
            asyncio.create_task(_close())

    def _agent_turn(self, req: Request, tid: int) -> str:
        """One request, possibly many tool rounds. Runs in a worker thread."""
        b = brain_config.get_brain()
        s = llm.settings_for("chat")
        decls = self._all_tool_decls()
        params_by_name = {d.get("name"): d.get("parameters") for d in decls}
        now = datetime.now().strftime("%H:%M")
        user_msg: dict = {"role": "user", "content": f"{req.text}\n\n(time now {now})"
                          if req.source in ("voice", "typed") else req.text}
        if req.images:
            user_msg["images"] = req.images
        with self._hist_lock:
            self._history.append(user_msg)
        self._trim_history(s.num_ctx)
        spoken_all: list[str] = []
        self._turn_shown = []
        acked = False
        max_steps = int(b.get("max_steps", 10))
        tool_limit = max(1500, min(6000, int(s.num_ctx * 0.35)))

        for step in range(max_steps):
            if tid != self._turn_id or self._cancel.is_set():
                return " ".join(spoken_all)
            with self._hist_lock:
                msgs = [{"role": "system", "content": self._system_prompt()}] + list(self._history)
            stream = SpeechStream()
            final_ev = None
            try:
                for ev in llm.stream_chat(msgs, decls, s=s, cancel=self._cancel):
                    if ev.kind == "text":
                        for sentence in stream.feed(ev.text):
                            spoken_all.append(sentence)
                            self._speak(sentence, tid)
                    else:
                        final_ev = ev
            except llm.ProviderUnreachable as e:
                self._brain_ok = False
                msg = "I can't reach my brain right now."
                self.ui.write_log(f"ERR: {e}")
                self._speak(msg, tid)
                with self._hist_lock:
                    if self._history and self._history[-1] is user_msg:
                        self._history.pop()
                return msg
            except Exception as e:
                self.ui.write_log(f"ERR: Brain — {str(e)[:220]}")
                msg = "Something went wrong with the model: " + str(e)[:100]
                self._speak("Something went wrong with the model.", tid)
                with self._hist_lock:
                    if self._history and self._history[-1] is user_msg:
                        self._history.pop()
                return msg
            if final_ev is None or final_ev.cancelled:
                for sentence in stream.flush():
                    spoken_all.append(sentence)
                    self._speak(sentence, tid)
                return " ".join(spoken_all)
            for sentence in stream.flush():
                spoken_all.append(sentence)
                self._speak(sentence, tid)

            text = llm.strip_thinking(visible_text(final_ev.text))
            if text:
                self._turn_shown.append(text)
            calls = final_ev.tool_calls
            with self._hist_lock:
                self._history.append({"role": "assistant", "content": text,
                                      "tool_calls": [c.as_dict() for c in calls]} if calls
                                     else {"role": "assistant", "content": text})
            if not calls:
                return " ".join(spoken_all) or text

            if not spoken_all and not acked and any(c.name not in _INSTANT_TOOLS for c in calls):
                acked = True
                lang = self._last_lang if self._last_lang in _ACKS else "en"
                self._speak(random.choice(_ACKS[lang]), tid)

            self.ui.set_state("THINKING")
            for call in calls:
                if tid != self._turn_id or self._cancel.is_set():
                    break
                from core.tool_schema import coerce_arguments
                args = coerce_arguments(call.arguments, params_by_name.get(call.name))
                if call.name not in params_by_name:
                    result = (f"There is no tool named '{call.name}'. Use one of the listed tools.")
                else:
                    result = self._run_tool(call.name, args, call.id)
                extra_user = None
                if call.name == "screen_process" and self._pending_vision:
                    result, extra_user = self._resolve_vision(s)
                result = str(result)
                if len(result) > tool_limit:
                    result = result[:tool_limit] + f"\n…[truncated {len(result) - tool_limit} chars]"
                with self._hist_lock:
                    self._history.append({"role": "tool", "tool_call_id": call.id, "name": call.name,
                                          "content": result})
                    if extra_user:
                        self._history.append(extra_user)
        self._speak("I've stopped there — that took more steps than I allow myself. "
                    "Tell me if you want me to continue.", tid)
        return " ".join(spoken_all)

    def _run_tool(self, name: str, args: dict, call_id: str) -> str:
        if name == "shutdown_jarvis":
            return self._local_shutdown()
        loop = self._loop
        fc = SimpleNamespace(name=name, args=args, id=call_id or "")

        async def go():
            fr = await self._execute_tool(fc)
            resp = getattr(fr, "response", None) or {}
            return str(resp.get("result", "Done.")) if isinstance(resp, dict) else str(resp)
        try:
            return asyncio.run_coroutine_threadsafe(go(), loop).result()
        except Exception as e:
            return f"Tool '{name}' failed: {e}"

    def _local_shutdown(self) -> str:
        def bye():
            time.sleep(0.3)
            self._wait_tts(self._turn_id, timeout=8)
            time.sleep(1.0)
            try:
                fut = asyncio.run_coroutine_threadsafe(self._save_session_summary(), self._loop)
                fut.result(timeout=20)
            except Exception:
                pass
            import os
            os._exit(0)
        threading.Thread(target=bye, daemon=True).start()
        return "Shutting down now. Say a brief goodbye in one short sentence."

    def _resolve_vision(self, s: llm.Settings):
        """screen_process captured a frame: show it to a model that can see."""
        img_b, mime, question, angle = self._pending_vision
        self._pending_vision = None
        if self._vision_cam_active:
            self._vision_cam_active = False
            self._vision_close_pending = True
        self._vision_busy = False
        src = "WEBCAM" if angle == "camera" else "SCREEN CAPTURE"
        part = llm.image_part(img_b, mime)
        caps = llm.capabilities(s)
        vision_model = brain_config.get_brain().get("vision_model") or ""
        if caps.get("vision") and (not vision_model or vision_model == s.model):
            return ("The image is attached in the next message. Answer from what you see.",
                    {"role": "user", "content": f"[IMAGE SOURCE: {src}] {question}", "images": [part]})
        if vision_model:
            try:
                desc = llm.complete([f"[IMAGE SOURCE: {src}] {question}\nDescribe precisely what is "
                                     "relevant, including any readable text.", part],
                                    role="vision", max_tokens=600, timeout=120)
                if desc:
                    return f"[What the {angle} shows, described by the vision model]\n{desc}", None
            except Exception as e:
                self.ui.write_log(f"ERR: Vision model — {str(e)[:160]}")
        if angle != "camera":
            try:
                from core import screen_reader
                text = screen_reader.ocr_image_bytes(img_b)
                if text:
                    return ("No vision model is set, so here is the text read from the screen "
                            f"(OCR):\n{text}"), None
            except Exception:
                pass
        return ("I captured the image but no model that can see is configured. Tell the user to "
                "pick a vision model (for example qwen2.5vl:3b or gemma3:4b) in ⚙ → AI BRAIN."), None
