"""
skill_manager — the assistant teaches itself.

Two kinds of skill:

  Routines   a named list of steps in plain language ("morning routine: read
             the weather, open Outlook, summarise unread mail, play lo-fi on
             YouTube"). Saving one is instant; "run my morning routine" hands the
             steps back to the assistant, which carries them out with its tools.

  Tools      a brand-new Python plugin written for a job no existing tool does
             ("a tool that reads my Fitbit export", "check a website for price
             drops"). The code is generated by the smart model, checked, shown
             on screen, and saved to plugins/ ONLY after the user confirms (by
             button or by saying "confirm") — new code is never installed
             silently. It is usable at once, no restart.
"""
from __future__ import annotations

import ast
import json
import re
import threading
from pathlib import Path

from core import confirm as confirm_gate
from core import llm, runtime

_BASE = Path(__file__).resolve().parent.parent
PLUGINS = _BASE / "plugins"
ROUTINES = _BASE / "memory" / "routines.json"
_lock = threading.Lock()

_TEMPLATE_RULES = """Write ONE complete Python file for a JARVIS plugin. Requirements:
- Module-level dict PLUGIN = {"name": "<snake_case>", "description": "<when to use it>",
  "parameters": {"type": "OBJECT", "properties": {<name>: {"type": "STRING"|"INTEGER"|"NUMBER"|"BOOLEAN",
  "description": "..."}}, "required": [...]}}   (types are UPPERCASE)
- A function  def run(parameters: dict, player=None) -> str  that does the work and returns a
  short plain-English result. It must catch its own exceptions and return an error sentence.
- Standard library first; you may also use: requests, bs4, psutil, pyautogui, pyperclip, PIL,
  numpy, cv2, openpyxl, docx, pptx, pdfplumber. Import heavy modules inside run().
- Paths: use pathlib and Path.home(); never delete files outside what the task needs.
- No input(), no infinite loops, network calls with timeout=.
Output ONLY the Python code, no markdown fences."""


def _load_routines() -> dict:
    try:
        return json.loads(ROUTINES.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _save_routines(data: dict) -> None:
    ROUTINES.parent.mkdir(parents=True, exist_ok=True)
    ROUTINES.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def validate_plugin_source(code: str) -> tuple[bool, str, str]:
    """(ok, message, plugin_name)."""
    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        return False, f"syntax error on line {e.lineno}: {e.msg}", ""
    name = ""
    has_run = False
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "PLUGIN" for t in node.targets):
            try:
                meta = ast.literal_eval(node.value)
                name = str(meta.get("name", ""))
                if meta.get("parameters", {}).get("type") != "OBJECT":
                    return False, "PLUGIN['parameters']['type'] must be \"OBJECT\"", name
            except Exception:
                return False, "PLUGIN must be a plain literal dict", ""
        if isinstance(node, ast.FunctionDef) and node.name == "run":
            has_run = True
    if not re.fullmatch(r"[a-z_][a-z0-9_]{1,50}", name or ""):
        return False, "PLUGIN['name'] missing or not snake_case", name
    if not has_run:
        return False, "no run(parameters, player=None) function", name
    banned = re.search(r"\b(shutil\.rmtree\(\s*['\"]?[A-Za-z]:\\\\?['\"]?\)|os\.system\(\s*['\"](format|del /s))", code)
    if banned:
        return False, "the code contains a destructive system call", name
    return True, "ok", name


def _generate(request: str, name_hint: str = "") -> str:
    prompt = f"{_TEMPLATE_RULES}\n\nThe tool to write: {request}"
    if name_hint:
        prompt += f"\nUse the plugin name: {name_hint}"
    code = llm.complete(prompt, system="You write small, correct, well-structured Python plugins.",
                        role="smart", max_tokens=3500, timeout=240)
    code = re.sub(r"^```(?:python)?\s*|\s*```\s*$", "", code.strip())
    return code


def _install(name: str, code: str) -> str:
    path = PLUGINS / f"{name}.py"
    path.write_text(code, encoding="utf-8")
    res = runtime.reload_tools()
    runtime.inject(f"[TOOL_RESULT] The new skill '{name}' is installed ({res}). Tell the user in one "
                   f"sentence that it is ready and how to use it.")
    return f"Installed {path.name}. {res}"


def skill_manager(parameters: dict, player=None) -> str:
    p = parameters or {}
    action = str(p.get("action") or "list").lower().strip()
    name = re.sub(r"[^a-z0-9_]", "_", str(p.get("name") or "").lower()).strip("_")

    if action == "save_routine":
        steps = str(p.get("steps") or p.get("request") or "").strip()
        if not name or not steps:
            return "A routine needs a name and its steps."
        with _lock:
            data = _load_routines()
            data[name] = steps
            _save_routines(data)
        return f"Saved the routine '{name}'."
    if action == "run_routine":
        data = _load_routines()
        key = name if name in data else next((k for k in data if name and (name in k or k in name)), "")
        if not key:
            return f"No routine called '{name}'. Known: {', '.join(data) or 'none'}."
        return (f"[ROUTINE {key}] Carry out these steps now, in order, using your tools, then report "
                f"briefly:\n{data[key]}")
    if action == "delete_routine":
        with _lock:
            data = _load_routines()
            if data.pop(name, None) is None:
                return f"No routine called '{name}'."
            _save_routines(data)
        return f"Deleted the routine '{name}'."

    if action == "list":
        routines = _load_routines()
        tools = sorted(f.stem for f in PLUGINS.glob("*.py") if not f.name.startswith("_"))
        return (f"Routines: {', '.join(routines) or 'none'}. "
                f"Plugin tools: {', '.join(tools) or 'none'}.")
    if action == "show":
        f = PLUGINS / f"{name}.py"
        if not f.exists():
            return f"No plugin called '{name}'."
        code = f.read_text(encoding="utf-8")
        if player:
            try:
                player.show_content(f"SKILL — {name}", code)
            except Exception:
                pass
        return f"The code of {name} is on screen ({len(code.splitlines())} lines)."
    if action == "delete":
        f = PLUGINS / f"{name}.py"
        if not f.exists() or name.startswith("_") or name in ("smart_home", "maker_hardware"):
            return f"'{name}' cannot be deleted this way."
        return confirm_gate.request("skill-delete", f"Delete the skill '{name}'?", str(f),
                                    lambda: (f.unlink(), runtime.reload_tools())[1])
    if action == "reload":
        return runtime.reload_tools()
    if action in ("create", "create_tool", "new"):
        code = str(p.get("code") or "").strip()
        request = str(p.get("request") or "").strip()
        if not code:
            if not request:
                return "Describe what the new tool should do."
            try:
                code = _generate(request, name)
            except Exception as e:
                return f"Could not generate the code: {e}"
        ok, msg, pname = validate_plugin_source(code)
        if not ok:
            try:
                code = _generate(f"{request}\nThe previous attempt failed validation: {msg}. Fix it.", name)
                ok, msg, pname = validate_plugin_source(code)
            except Exception:
                pass
        if not ok:
            return f"The generated tool did not pass checks ({msg}). Nothing was installed."
        if (PLUGINS / f"{pname}.py").exists() and not p.get("overwrite"):
            return f"A plugin named '{pname}' already exists. Ask again with overwrite to replace it."
        if player:
            try:
                player.show_content(f"NEW SKILL — {pname}", code)
            except Exception:
                pass
        return confirm_gate.request(
            "skill-install", f"Install the new skill '{pname}'?",
            f"{len(code.splitlines())} lines of Python — the code is shown below the HUD.",
            lambda: _install(pname, code))
    return "Unknown action."


TOOL = {
    "name": "skill_manager",
    "description": (
        "Teach yourself new abilities. save_routine / run_routine / delete_routine store and replay a "
        "named multi-step routine in plain language. create writes a brand-new Python tool from a "
        "description (shown to the user and installed after they confirm); list, show, delete, reload "
        "manage installed skills."
    ),
    "parameters": {
        "type": "OBJECT",
        "properties": {
            "action": {"type": "STRING",
                       "description": "save_routine | run_routine | delete_routine | create | list | show | delete | reload"},
            "name": {"type": "STRING", "description": "Routine or tool name (snake_case)"},
            "steps": {"type": "STRING", "description": "For save_routine: the steps in order"},
            "request": {"type": "STRING", "description": "For create: what the new tool must do"},
            "code": {"type": "STRING", "description": "For create: full plugin source, if you wrote it yourself"},
            "overwrite": {"type": "BOOLEAN", "description": "Replace an existing tool"},
        },
        "required": ["action"],
    },
    "handler": skill_manager,
}
